FROM rust:1.70-buster as builder

WORKDIR /usr/src/moskino-tg-bot

COPY bot bot/
COPY db db/
COPY .env bot/

# do not analyze sql queries via connecting to DB during compile
ENV SQLX_OFFLINE=true

RUN cargo install --path bot





FROM debian:buster-slim
RUN apt update && apt install -y \
    openssl \
    ca-certificates

WORKDIR /usr/local/bin

COPY --from=builder /usr/src/moskino-tg-bot/bot/target/release/bot .
COPY db/migrations .

CMD ["bot"]